import Foundation

// MARK: - Task Model
/// Represents a single actionable task generated by Sage.
/// Tasks are designed to be small (10-40 minutes) and achievable.
struct SageTask: Identifiable, Codable, Equatable {
    
    /// Unique identifier
    let id: UUID
    
    /// Task title - short, actionable description
    let title: String
    
    /// Optional detailed description
    var description: String?
    
    /// Estimated time in minutes (10-40)
    var estimatedMinutes: Int
    
    /// Current status
    var status: TaskStatus
    
    /// Parent goal ID
    var goalId: UUID?
    
    /// Order in the task sequence
    var order: Int
    
    /// When the task was created
    let createdAt: Date
    
    /// When the task was completed (if applicable)
    var completedAt: Date?
    
    /// Encouragement message from Sage for this task
    var sageMessage: String?
    
    // MARK: - Initialization
    
    init(
        id: UUID = UUID(),
        title: String,
        description: String? = nil,
        estimatedMinutes: Int = 15,
        status: TaskStatus = .pending,
        goalId: UUID? = nil,
        order: Int = 0,
        sageMessage: String? = nil
    ) {
        self.id = id
        self.title = title
        self.description = description
        self.estimatedMinutes = min(max(estimatedMinutes, 5), 60) // Clamp between 5-60
        self.status = status
        self.goalId = goalId
        self.order = order
        self.createdAt = Date()
        self.completedAt = nil
        self.sageMessage = sageMessage
    }
    
    // MARK: - Computed Properties
    
    /// Human-readable time estimate
    var timeEstimate: String {
        if estimatedMinutes < 60 {
            return "\(estimatedMinutes) min"
        } else {
            let hours = estimatedMinutes / 60
            let mins = estimatedMinutes % 60
            return mins > 0 ? "\(hours)h \(mins)m" : "\(hours)h"
        }
    }
    
    /// Whether the task is actionable
    var isActionable: Bool {
        status == .pending || status == .inProgress
    }
    
    // MARK: - Mutations
    
    /// Marks the task as completed
    mutating func complete() {
        status = .completed
        completedAt = Date()
    }
    
    /// Marks the task as skipped
    mutating func skip() {
        status = .skipped
    }
    
    /// Starts the task
    mutating func start() {
        status = .inProgress
    }
}

// MARK: - Task Status

enum TaskStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case inProgress = "in_progress"
    case completed = "completed"
    case skipped = "skipped"
    
    var displayName: String {
        switch self {
        case .pending: return "To Do"
        case .inProgress: return "In Progress"
        case .completed: return "Done"
        case .skipped: return "Skipped"
        }
    }
    
    var icon: String {
        switch self {
        case .pending: return "circle"
        case .inProgress: return "circle.dotted"
        case .completed: return "checkmark.circle.fill"
        case .skipped: return "forward.circle"
        }
    }
}
